name: Build Windows
on:
  workflow_call:
    inputs:
      app_version: { required: true, type: string }
      build_number: { required: true, type: string }

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
      APP_BUILD_NUMBER: ${{ inputs.build_number }}
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: bash .github/scripts/build.sh windows
      - uses: actions/upload-artifact@v7
        with:
          name: windows-build
          path: build/windows/x64/runner/Release/
