name: Build iOS
on:
  workflow_call:
    inputs:
      app_version: { required: true, type: string }
      build_number: { required: true, type: string }

jobs:
  build:
    name: Build iOS
    runs-on: macos-latest
    env:
      APP_VERSION: ${{ inputs.app_version }}
      APP_BUILD_NUMBER: ${{ inputs.build_number }}
    steps:
      - uses: actions/checkout@v7
      - uses: subosito/flutter-action@v2
        with: { channel: stable }
      - run: bash .github/scripts/build.sh ios
      - uses: actions/upload-artifact@v7
        with:
          name: ios-build
          path: build/ios/iphoneos/
